baseURL      = "https://smolka.dev/"
title        = "Smolka"
copyright    = "Julian Smolka"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[author]
  name = "Julian Smolka"

[params]
  description     = "Mediocre posts about emulation and micro optimizations."
  contentUrl      = "https://github.com/jsmolka/jsmolka.github.io/tree/source/content"
  birthDate       = "1998-05-11"
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  language        = "en-US"

[menu]
  [[menu.main]]
    name = "About"
    url  = "/about"

  [[menu.main]]
    name = "Cycling"
    url  = "/cycling"

  [[menu.main]]
    name = "Eggvance"
    url  = "/eggvance"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      typographer = false

    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    codeFences = false

[module]
  [[module.mounts]]
    source = "static/CNAME"
    target = "static/CNAME"

  [[module.mounts]]
    source = "static/audio"
    target = "static/static/audio"

  [[module.mounts]]
    source = "static/data"
    target = "static/static/data"

  [[module.mounts]]
    source = "static/font"
    target = "static/static/font"

  [[module.mounts]]
    source = "static/icon"
    target = "static/static/icon"

  [[module.mounts]]
    source = "static/img"
    target = "static/static/img"

  [[module.mounts]]
    source = "static/wasm"
    target = "static/static/wasm"

  [[module.mounts]]
    source = "icon/website/web"
    target = "static"
